### ISSUE TITLE
Chapter10- camel-cxf-rest-spring-boot -java.lang.String cannot be cast to org.apache.cxf.feature.Feature

### ISSUE THREAD

**Issue by imranrazakhan** [camelinaction/camelinaction2#103]
Hi,
I tried to add swagger support in "camel-cxf-rest-spring-boot"

in OrderRoute  i added below code

    @Bean(name = "featuresList")
    public Set<Object> getFeaturesList() {
        Swagger2Feature swagger = new Swagger2Feature();
        swagger.setBasePath("/");
        swagger.setHost("localhost:9000");
        swagger.setTitle("Order Service");
        swagger.setDescription("Rider Auto Parts Order Service");
        swagger.setVersion("2.0.0");
        swagger.setContact("rider@autoparts.com");
        swagger.setPrettyPrint(true);
        Set<Object> answer = new HashSet<>();
        answer.add(swagger);
        return answer;
    }

add features in route like below

    from("cxfrs:http://localhost:8080?resourceClasses=camelinaction.RestOrderService&bindingStyle=SimpleConsumer&providers=#jsonProvider&features=#featuresList")

but its throwing following error

2017-11-18 03:39:20 ERROR o.s.b.SpringApplication:771 - Application startup failed
org.apache.camel.RuntimeCamelException: org.apache.camel.FailedToCreateRouteException: Failed to create route route1: Route(route1)[[From[cxfrs:http://localhost:8080?resourceClas... because of ServiceConstructionException
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1831)
	at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:136)
	at org.apache.camel.spring.SpringCamelContext.onApplicationEvent(SpringCamelContext.java:174)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at org.restcomm.charging.ChargingApplication.main(ChargingApplication.java:17)
Caused by: org.apache.camel.FailedToCreateRouteException: Failed to create route route1: Route(route1)[[From[cxfrs:http://localhost:8080?resourceClas... because of ServiceConstructionException
	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:147)
	at org.apache.camel.impl.DefaultCamelContext.doWarmUpRoutes(DefaultCamelContext.java:3945)
	at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3852)
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3638)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3490)
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:208)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3249)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3245)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3268)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3245)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3168)
	at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:133)
	... 14 common frames omitted
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: null
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:225)
	at org.apache.camel.component.cxf.jaxrs.CxfRsConsumer.createServer(CxfRsConsumer.java:63)
	at org.apache.camel.component.cxf.jaxrs.CxfRsConsumer.<init>(CxfRsConsumer.java:43)
	at org.apache.camel.component.cxf.jaxrs.CxfRsEndpoint.createConsumer(CxfRsEndpoint.java:191)
	at org.apache.camel.impl.EventDrivenConsumerRoute.addServices(EventDrivenConsumerRoute.java:69)
	at org.apache.camel.impl.DefaultRoute.onStartingServices(DefaultRoute.java:103)
	at org.apache.camel.impl.RouteService.doWarmUp(RouteService.java:172)
	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:145)
	... 26 common frames omitted
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.cxf.feature.Feature
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.applyFeatures(JAXRSServerFactoryBean.java:265)
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:197)

**Comment by imranrazakhan** [comment]
Hi,
My bad,  i suppose to provide List<Feature> to route, now its working fine.

Any help to get swagger-ui through cxfrs.
Regard

**Comment by davsclaus** [comment]
Ah okay you changed to

    public List<Object> getFeaturesList() {
