### ISSUE TITLE
chapter10 - geocoder now requires api keys

### ISSUE THREAD

**Issue by davsclaus** [camelinaction/camelinaction2#141]
java.lang.IllegalStateException: Must provide either API key or Maps for Work credentials.
	at com.google.maps.GeoApiContext.checkContext(GeoApiContext.java:293) ~[google-maps-services-0.2.9.jar:na]
	at com.google.maps.GeoApiContext.getWithPath(GeoApiContext.java:258) ~[google-maps-services-0.2.9.jar:na]
	at com.google.maps.GeoApiContext.get(GeoApiContext.java:168) ~[google-maps-services-0.2.9.jar:na]

**Comment by changzhiwin** [comment]
got it, thanks.
