### ISSUE TITLE
Chapter 2 - Failure in unit test

### ISSUE THREAD

**Issue by davsclaus** [camelinaction/camelinaction2#18]
Running camelinaction.FtpToJMSWithDynamicToTest

```
2016-12-23 13:23:22,773 [file://src/data] ERROR DefaultErrorHandler            - Failed delivery for (MessageId: ID-davsclaus-air-50597-1482495800323-0-1 on ExchangeId: ID-davsclaus-air-50597-1482495800323-0-2). Exhausted after delivery attempt: 1 caught: java.util.concurrent.RejectedExecutionException

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[route1            ] [route1            ] [file://src/data?noop=true                                                     ] [        63]
[route1            ] [setHeader1        ] [setHeader[myDest]                                                             ] [         4]
[route1            ] [toD1              ] [                                                                              ] [        42]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
java.util.concurrent.RejectedExecutionException
	at org.apache.camel.component.jms.JmsProducer.process(JmsProducer.java:141)
	at org.apache.camel.processor.SendDynamicProcessor$1.doInAsyncProducer(SendDynamicProcessor.java:124)
	at org.apache.camel.impl.ProducerCache.doInAsyncProducer(ProducerCache.java:436)
	at org.apache.camel.processor.SendDynamicProcessor.process(SendDynamicProcessor.java:119)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:542)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
	at org.apache.camel.component.file.GenericFileConsumer.processExchange(GenericFileConsumer.java:460)
	at org.apache.camel.component.file.GenericFileConsumer.processBatch(GenericFileConsumer.java:227)
	at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:191)
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:175)
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by davsclaus** [comment]
Cannot reproduce

**Comment by hemangajmera** [comment]
I got the same issue

**Comment by hemangajmera** [comment]
@davsclaus Can this be re-opened?

``
Running camelinaction.FtpToJMSWithDynamicToTest
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/ajmerah/.m2/repository/org/apache/activemq/activemq-all/5.15.4/activemq-all-5.15.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/ajmerah/.m2/repository/org/slf4j/slf4j-log4j12/1.7.21/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2018-06-12 10:31:06,652 [main           ] INFO  FtpToJMSWithDynamicToTest      - ********************************************************************************
2018-06-12 10:31:06,654 [main           ] INFO  FtpToJMSWithDynamicToTest      - Testing: testPlacingOrders(camelinaction.FtpToJMSWithDynamicToTest)
2018-06-12 10:31:06,654 [main           ] INFO  FtpToJMSWithDynamicToTest      - ********************************************************************************
2018-06-12 10:31:07,434 [main           ] INFO  DefaultCamelContext            - Apache Camel 2.21.1 (CamelContext: camel-1) is starting
2018-06-12 10:31:07,437 [main           ] INFO  DefaultManagementStrategy      - JMX is disabled
2018-06-12 10:31:07,552 [main           ] INFO  DefaultTypeConverter           - Type converters loaded (core: 194, classpath: 4)
2018-06-12 10:31:07,810 [main           ] INFO  DefaultCamelContext            - StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
2018-06-12 10:31:07,821 [main           ] INFO  FileEndpoint                   - Endpoint is configured with noop=true so forcing endpoint to be idempotent as well
2018-06-12 10:31:07,821 [main           ] INFO  FileEndpoint                   - Using default memory based idempotent repository with cache max size: 1000
2018-06-12 10:31:07,985 [main           ] INFO  DefaultCamelContext            - Route: route1 started and consuming from: file://src/data?noop=true
2018-06-12 10:31:09,061 [file://src/data] ERROR DefaultErrorHandler            - Failed delivery for (MessageId: ID-INL-3HWR6C2-1528779666824-0-2 on ExchangeId: ID-INL-3HWR6C2-1528779666824-0-1). Exhausted after delivery attempt: 1 caught: java.util.concurrent.RejectedExecutionException

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[route1            ] [route1            ] [file://src/data?noop=true                                                     ] [        47]
[route1            ] [setHeader1        ] [setHeader[myDest]                                                             ] [        15]
[route1            ] [toD1              ] [                                                                              ] [        16]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
java.util.concurrent.RejectedExecutionException
        at org.apache.camel.component.jms.JmsProducer.process(JmsProducer.java:144)
        at org.apache.camel.processor.SendDynamicProcessor$1.doInAsyncProducer(SendDynamicProcessor.java:132)
        at org.apache.camel.impl.ProducerCache.doInAsyncProducer(ProducerCache.java:445)
        at org.apache.camel.processor.SendDynamicProcessor.process(SendDynamicProcessor.java:127)
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
        at org.apache.camel.component.file.GenericFileConsumer.processExchange(GenericFileConsumer.java:452)
        at org.apache.camel.component.file.GenericFileConsumer.processBatch(GenericFileConsumer.java:219)
        at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:183)
        at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174)
        at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-06-12 10:31:09,070 [file://src/data] WARN  GenericFileOnCompletion        - Rollback file strategy: org.apache.camel.component.file.strategy.GenericFileRenameProcessStrategy@2769a009 for file: GenericFile[message1.xml]

**Comment by hemangajmera** [comment]
When I ran from CMD it worked fine. The issue is coming if code is executed from Git Bash. Not sure about the reason, but it seem the ActiveMQ could not start from Git Bash.

**Comment by hemangajmera** [comment]
I am getting the same error. I am running it on Windows.
@davsclaus, can you please reopen it.

Please note that if I use .to instead of .toD, the code works fine.

```java
                from("file:src/data?noop=true")
                    .to("jms:incomingOrders")
                    ;
                    // .setHeader("myDest", constant("incomingOrders"))
                    // .toD("jms:${header.myDest}");
```
